services:
  backend:
    build:
      context: .
      dockerfile: ${DOCKERFILE_PATH:-Dockerfile}
      args:
        - ENV=${ENV:-production}
    container_name: codex-backend
    restart: unless-stopped  # Keep trying to restart if it crashes
    command: ["bash", "/app/scripts/docker-entrypoint.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s  # Increased to allow more time for startup
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=${ENV:-production}
      - REDIS_URL=redis://redis:6379
      - SQLITE_DB_PATH=/app/app/db/chat_memory.db
      - OLLAMA_BASE_URL=http://ollama:11434
      - PYTHONPATH=${PYTHONPATH:-/app}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY:-}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-}
      - STRIPE_PRO_MONTHLY_PRICE_ID=${STRIPE_PRO_MONTHLY_PRICE_ID:-}
      - STRIPE_PRO_ANNUAL_PRICE_ID=${STRIPE_PRO_ANNUAL_PRICE_ID:-}
      - STRIPE_BUSINESS_MONTHLY_PRICE_ID=${STRIPE_BUSINESS_MONTHLY_PRICE_ID:-}
      - STRIPE_BUSINESS_ANNUAL_PRICE_ID=${STRIPE_BUSINESS_ANNUAL_PRICE_ID:-}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-supersecretjwtkey}
      - PASSWORD_SALT=${PASSWORD_SALT:-securepasswordsalt}
      # Stripe CLI settings
      - INSTALL_STRIPE_CLI=${INSTALL_STRIPE_CLI:-true}
    volumes:
      # In development, mount the entire code directory for debugging
      - .:/app
      # If you're using the Stripe CLI for webhook testing
      - ${HOME:-/root}/.config/stripe:/root/.config/stripe
    depends_on:
      - redis
      - ollama
    networks:
      - codexnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: codex-frontend
    # Using the default CMD from Dockerfile to run app.py
    # command: ["/app/run_fixed_app.sh"]
    ports:
      - "8501:8501"
    environment:
      - BACKEND_HOST=${BACKEND_HOST:-backend}
      - BACKEND_PORT=${BACKEND_PORT:-8000}
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - codexnet

  redis:
    image: redis:7
    container_name: codex-redis
    ports:
      - "6379:6379"
    networks:
      - codexnet

  ollama:
    image: ollama/ollama
    container_name: codex-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - codexnet
    restart: unless-stopped

volumes:
  ollama_data:

networks:
  codexnet:
    driver: bridge
